# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\decryptedTextWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DecryptedWindow(object):
    def setupUi(self, DecryptedWindow):
        DecryptedWindow.setObjectName("DecryptedWindow")
        DecryptedWindow.resize(407, 475)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ui\\icons/decrypted_window_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DecryptedWindow.setWindowIcon(icon)
        DecryptedWindow.setStyleSheet("background-color: #1F2933;")
        self.textBrowser = QtWidgets.QTextBrowser(DecryptedWindow)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 391, 451))
        self.textBrowser.setStyleSheet("background-color: #3E4C59;\n"
"font: 12pt \"Calibri\";\n"
"color: white;")
        self.textBrowser.setAcceptRichText(False)
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(DecryptedWindow)
        QtCore.QMetaObject.connectSlotsByName(DecryptedWindow)

    def retranslateUi(self, DecryptedWindow):
        _translate = QtCore.QCoreApplication.translate
        DecryptedWindow.setWindowTitle(_translate("DecryptedWindow", "Decrypted Text"))
        self.textBrowser.setHtml(_translate("DecryptedWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DecryptedWindow = QtWidgets.QWidget()
    ui = Ui_DecryptedWindow()
    ui.setupUi(DecryptedWindow)
    DecryptedWindow.show()
    sys.exit(app.exec_())
